/** Builds the shared data files the desktop (Rust) build embeds; see export-contracts.ts. */
import { PERSONAS } from '../src/backend/services/personas.js';
import { SKILLS_CATALOG } from '../src/backend/routes/skills.js';

export function personasContract() {
  return {
    $comment: 'Generated by scripts/export-contracts.ts from src/backend/services/personas.ts. Do not edit by hand.',
    personas: Object.fromEntries(
      Object.values(PERSONAS).map((persona) => [
        persona.id,
        { systemPrompt: persona.systemPrompt, toolAllowlist: persona.toolAllowlist ?? [] },
      ]),
    ),
  };
}

export function skillsCatalogContract() {
  return {
    $comment: 'Generated by scripts/export-contracts.ts from src/backend/routes/skills.ts. Do not edit by hand.',
    skills: SKILLS_CATALOG,
  };
}

